---
- name: Get server info
  azure.azcollection.azure_rm_postgresqlflexibleserver_info:
    resource_group: "{{ azure_manage_postgresqlflex_resource_group }}"
    name: "{{ azure_manage_postgresqlflex_name }}"
  register: azure_manage_postgresqlflex_server_info

- name: Get Resource group info
  azure.azcollection.azure_rm_resourcegroup_info:
    name: "{{ azure_manage_postgresqlflex_resource_group }}"
  register: azure_manage_postgresqlflex_rg_info

- name: Create or delete Azure PostgreSQL Flex server
  ansible.builtin.include_tasks: "{{ azure_manage_postgresqlflex_operation }}.yml"
