---
- name: Fail on invalid delete option
  ansible.builtin.fail:
    msg: Invalid value for azure_virtual_machine_with_public_ip_remove_on_absent. Valid values include 'all', 'all_autocreated', 'network_interfaces', 'virtual_storage', or 'public_ips'
  when: azure_virtual_machine_with_public_ip_remove_on_absent not in ['all', 'all_autocreated', 'network_interfaces', 'virtual_storage', 'public_ips']

- name: Delete Virtual Machine and specified associated resources
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ azure_virtual_machine_with_public_ip_resource_group }}"
    name: "{{ azure_virtual_machine_with_public_ip_vm_name }}"
    remove_on_absent: "{{ azure_virtual_machine_with_public_ip_remove_on_absent | default(omit) }}"
    state: absent

# Delete availability set if created by role
- name: Get availability set info
  azure.azcollection.azure_rm_availabilityset_info:
    resource_group: "{{ azure_virtual_machine_with_public_ip_resource_group }}"
    name: "{{ azure_virtual_machine_with_public_ip_availability_set.name }}"
    tags:
      _own_availability_set_
  register: azure_virtual_machine_with_public_ip_aset_info
  when: azure_virtual_machine_with_public_ip_availability_set is defined

- name: Delete availability set if created by role
  azure.azcollection.azure_rm_availabilityset:
    resource_group: "{{ azure_virtual_machine_with_public_ip_resource_group }}"
    name: "{{ azure_virtual_machine_with_public_ip_availability_set.name }}" 
    state: absent
  when:
    - azure_virtual_machine_with_public_ip_availability_set is defined
    - azure_virtual_machine_with_public_ip_aset_info.ansible_info.azure_availabilitysets | length == 1
    - azure_virtual_machine_with_public_ip_remove_on_absent in ['all', 'all_autocreated']

# Delete Virtual network if created by role
- name: Get virtual network info
  azure.azcollection.azure_rm_virtualnetwork_info:
    resource_group: "{{ azure_virtual_machine_with_public_ip_resource_group }}"
    name: "{{ azure_virtual_machine_with_public_ip_vm_name }}"
    tags:
      _own_vnet_
  register: azure_virtual_machine_with_public_ip_vnet_info

- name: Delete Virtual network if created by role
  azure.azcollection.azure_rm_virtualnetwork:
    resource_group: "{{ azure_virtual_machine_with_public_ip_resource_group }}"
    name: "{{ azure_virtual_machine_with_public_ip_vm_name }}"
    state: absent
  when:
    - azure_virtual_machine_with_public_ip_vnet_info.virtualnetworks | length == 1
    - azure_virtual_machine_with_public_ip_remove_on_absent in ['all', 'all_autocreated']

- name: Delete Resource group if requested
  ansible.builtin.include_role:
    name: cloud.azure_ops.azure_manage_resource_group
  vars:
    azure_manage_resource_group_operation: delete
    azure_manage_resource_group_name: "{{ azure_virtual_machine_with_public_ip_resource_group }}"
  when: azure_virtual_machine_with_public_ip_delete_resource_group
