---
- name: Verify that Resource Group exists - `{{ azure_load_balancer_with_public_ip_resource_group }}`
  ansible.builtin.fail:
    msg: Resource group '{{ azure_load_balancer_with_public_ip_resource_group }}' does not exist.
  when:
    - azure_load_balancer_with_public_ip_rg_info.resourcegroups | length == 0

- name: Get lb's public ip info
  azure.azcollection.azure_rm_resource_info:
    url: "{{ azure_load_balancer_with_public_ip_lb_info.loadbalancers[0].frontend_ip_configurations[0].public_ip_address.id }}"
  register: azure_load_balancer_with_public_ip_pip

- name: Delete load balancer
  azure.azcollection.azure_rm_loadbalancer:
    resource_group: "{{ azure_load_balancer_with_public_ip_resource_group }}"
    name: "{{ azure_load_balancer_with_public_ip_load_balancer.name }}"
    state: absent

- name: Delete load balancer's public ip
  azure.azcollection.azure_rm_publicipaddress:
    resource_group: "{{ azure_load_balancer_with_public_ip_resource_group }}"
    name: "{{ azure_load_balancer_with_public_ip_pip.response[0].name }}"
    state: absent

- name: Delete Resource Group if requested
  ansible.builtin.include_role:
    name: cloud.azure_ops.azure_manage_resource_group
  vars:
    azure_manage_resource_group_operation: delete
    azure_manage_resource_group_name: "{{ azure_load_balancer_with_public_ip_resource_group }}"
  when: azure_load_balancer_with_public_ip_delete_resource_group
