---
- name: Check operation validation
  ansible.builtin.fail:
    msg: Please provide azure_manage_networking_stack_operation as 'create' or 'delete'
  when: azure_manage_networking_stack_operation not in ['create', 'delete']

- name: Get resource group info
  azure.azcollection.azure_rm_resourcegroup_info:
    name: "{{ azure_manage_networking_stack_resource_group }}"
  register: azure_manage_networking_stack_rg_info

- name: Create or delete networking stack
  ansible.builtin.include_tasks: "{{ azure_manage_networking_stack_operation }}.yml"
